enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches-arsclib"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli-arsclib"
rv-brand = "ReVanced eXtended MNML"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
version = "auto"
excluded-patches = "'Hide recommended communities shelf' 'Premium icon'"
